# Fixed IP Assignments
# ====================
# This file defines per-network static MAC-to-IP mappings for Meraki DHCP reservations.
# Each top-level key is a network slug (e.g. studio_hub), matching your manifest.
# Each child key is a VLAN name (e.g. Internal, IoT).
# Each MAC address maps to:
#   - offset: integer offset from the start of the VLAN subnet
#   - name: optional friendly label
#   - tags: optional list of tags (for inventory or grouping)
#
# Defaults can be defined via YAML anchors to reduce repetition.

# 💾 Default tags (reused via <<: *defaults)
defaults: &vlan_defaults
  Internal: &internal_defaults
    tags: [Internal, static]
  IoT: &iot_defaults
    tags: [IoT, static]

# 📡 Static IP Assignments per network
studio_hub:
  Internal:
    #Apple Mobile Devices
    '7a:75:ce:d5:f2:40':
      offset: 20
      name: Apple M2 Max
      <<: *internal_defaults

    '9a:ac:a1:bc:c9:38':
      offset: 21
      name: Apple iPad Pro 12.9
      <<: *internal_defaults

    '2e:73:cb:0b:4f:7f':
      offset: 22
      name: Apple iPhone 15 Pro Max
      <<: *internal_defaults

    'fa:00:25:57:47:10':
      offset: 23
      name: Apple Watch Ultra
      <<: *internal_defaults

    'f6:14:32:b2:3f:95':
      offset: 24
      name: Apple Watch Series 7
      <<: *internal_defaults

    '2c:cf:67:27:21:f0':
      offset: 30
      name: Pi5 PoE Hat 01 Kali Linux
      <<: *internal_defaults

    '2c:cf:67:27:03:b5':
      offset: 31
      name: Pi5 PoE Hat 02 Arch Linux
      <<: *internal_defaults

    '2c:cf:67:27:01:b1':
      offset: 32
      name: Pi5 03 Ubuntu Linux
      <<: *internal_defaults

    '2c:cf:67:27:18:65':
      offset: 33
      name: Pi5 04 Ubuntu Linux
      <<: *internal_defaults

    #Apple Home Devices
    'a8:51:ab:a1:95:be':
      offset: 40
      name: Desk Apple TV 
      <<: *internal_defaults

    '34:fd:6a:29:b1:f2':
      offset: 41
      name: Mantle Apple TV
      <<: *internal_defaults

    'ac:bc:b5:d9:2a:65':
      offset: 42
      name: Apple HomePod White
      <<: *internal_defaults

    'ac:bc:b5:dc:f6:45':
      offset: 43
      name: Apple HomePod Black
      <<: *internal_defaults

    '4c:20:b8:dd:89:e1':
      offset: 44
      name: Apple HomePod Mini White
      <<: *internal_defaults

    '58:d3:49:1a:fb:cd':
      offset: 45
      name: Apple HomePod Mini Black 01
      <<: *internal_defaults

    'f4:34:f0:06:6d:cb':
      offset: 46
      name: Apple HomePod Mini Black 02
      <<: *internal_defaults
    
  #Philips Hue Devices
    'ec:b5:fa:85:a3:35':
      offset: 50
      name: Pillips Hue Hub
      <<: *internal_defaults

  #Meross Power & Thermostat Devices
    '48:E1:E9:B1:F6:4B':
      offset: 60
      name: Cabinet PDU L01
      <<: *internal_defaults

    '48:E1:E9:B1:F7:B8':
      offset: 61
      name: Cabinet PDU L01
      <<: *internal_defaults
    
    '48:E1:E9:B1:FB:E6':
      offset: 62
      name: Cabinet PDU R02
      <<: *internal_defaults
    
    '48:E1:E9:B1:FA:5A':
      offset: 63
      name: Cabinet PDU M03
      <<: *internal_defaults

    '48:E1:E9:9C:EA:89':
      offset: 64
      name: Thermostat
      <<: *internal_defaults

studio_spoke:
  Internal:   
    'd8:3a:dd:f4:2d:a7':
      offset: 32
      name: Pi5 05 Ubuntu Linux
      <<: *internal_defaults
    
    '34:fd:6a:29:b1:f2':
      offset: 40
      name: Cabinet Apple TV
      <<: *internal_defaults