# config/defaults.yaml
#
# 🧰 Global Defaults — Applied to all orgs/networks unless overridden in project config.
# These values reduce repetition and promote consistency.

# 📦 Backend Provider (currently local only)
#
# All data (devices, VLANs, firewall rules, etc.) is read from local YAML files.
# Advanced users can later enable hybrid or remote backends (e.g., NetBox, InfraHub).
# To do this, add an `overrides` section under backend_providers.
# backend_providers:
#   default: local
#   overrides:
#     fixed_assignments: netbox
#     devices: infrahub

backend_providers:
  default: local  # Uses backend/local_yaml_backend.py for all config sources


# These defaults apply to all orgs/networks unless overridden by VLAN config
ipam:
  supernet: 10.0.0.0/8
  allocation:
    on_prem_prefix: 10    # for possible future use (unused for now)
    network_prefix: 16    # each network gets a /16
    vlan_prefix: 24       # each VLAN gets a /24 unless overridden
  reserved:
    - 10.0.0.0/13   # 10.0.0.0 → 10.7.255.255
    - 10.8.0.0/14   # 10.8.0.0 → 10.11.255.255
    - 10.12.0.0/14  # 10.12.0.0 → 10.15.255.255
    - 10.16.0.0/15  # 10.16.0.0 → 10.17.255.255

naming:
  # 📛 Device Naming Template
  # This defines how device names are generated. Each placeholder must match a key resolved from either:
  # 1. A matched rule (based on type + tags)
  # 2. The device’s location (from devices.yaml)
  # 3. These local naming defaults
  # 4. Legacy top-level naming keys (e.g., naming.city)

  template: "{city}-{building}-{room}-{function}-{type}"

  # 🧱 Default values if not overridden in rules or device metadata
  defaults:
    city: LON
    building: Percy
    room: Studio

  # 🧠 Rule-based overrides based on device type and tags
  # These let you assign more specific function names or naming values per device role
  rules:
    - match:
        type: MS
        tags: [access-switch]
      function: access

    - match:
        type: MS
        tags: [core-switch]
      function: aggregation

    - match:
        type: MS
        tags: [edge-switch]
      function: edge

    - match:
        type: MX
        tags: [hub-vpn]
      function: hub

    - match:
        type: MX
        tags: [spoke-vpn]
      function: spoke

organization:
  tags: [python-sdk]
  notes: "Auto-created by Python SDK"

network:
  type: combined
  time_zone: Europe/London
  tags: [python-sdk]
  notes: "Auto-created network"

management_vlan:
  name: MGMT
  id: 10

fallbacks:
  ms_port_profile: "Internal" # Default port profile for MS switches