Internal:
  00:22:33:44:55:66:
    ip: 10.10.20.200
    name: Internal Device 1
    tags:
      - Internal
      - static
  00:22:33:44:55:77:
    ip: 10.10.20.201
    name: Internal Device 2
    tags:
      - Internal
      - static