# config/common/firewall.yaml
#
# 🔥 Meraki Firewall Configuration
#
# This file defines L3 firewall rules applied to MX appliances.
# Both outbound (egress) and inbound (inter-VLAN) rules are supported.
#
# ✏️ Structure:
#   - outbound_rules: traffic leaving the MX to WAN
#   - inbound_rules: traffic between VLANs (inter-VLAN)
#
# ✅ VLAN-based syntax supported: use VLAN({id}).* or VLAN({id}).{host}
# ✅ Use "any" for wildcard IPs or ports
# ✅ syslogEnabled controls whether to log matched flows

outbound_rules:
  - comment: Allow traffic to AWS
    policy: allow
    protocol: tcp
    srcPort: any
    srcCidr: 10.10.10.0/24
    destPort: "443"
    destCidr: 10.100.0.0/16
    syslogEnabled: false

inbound_rules:
  - comment: Allow HTTP inbound between VLANs
    policy: allow
    protocol: tcp
    srcPort: any
    srcCidr: VLAN(10).*
    destPort: "80"
    destCidr: VLAN(20).*
    syslogEnabled: false